/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YeshivotRouteImport } from './routes/yeshivot'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YeshivotIdRouteImport } from './routes/yeshivot.$id'

const YeshivotRoute = YeshivotRouteImport.update({
  id: '/yeshivot',
  path: '/yeshivot',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YeshivotIdRoute = YeshivotIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => YeshivotRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/yeshivot': typeof YeshivotRouteWithChildren
  '/yeshivot/$id': typeof YeshivotIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/yeshivot': typeof YeshivotRouteWithChildren
  '/yeshivot/$id': typeof YeshivotIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/yeshivot': typeof YeshivotRouteWithChildren
  '/yeshivot/$id': typeof YeshivotIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/yeshivot' | '/yeshivot/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/yeshivot' | '/yeshivot/$id'
  id: '__root__' | '/' | '/admin' | '/yeshivot' | '/yeshivot/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  YeshivotRoute: typeof YeshivotRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yeshivot': {
      id: '/yeshivot'
      path: '/yeshivot'
      fullPath: '/yeshivot'
      preLoaderRoute: typeof YeshivotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yeshivot/$id': {
      id: '/yeshivot/$id'
      path: '/$id'
      fullPath: '/yeshivot/$id'
      preLoaderRoute: typeof YeshivotIdRouteImport
      parentRoute: typeof YeshivotRoute
    }
  }
}

interface YeshivotRouteChildren {
  YeshivotIdRoute: typeof YeshivotIdRoute
}

const YeshivotRouteChildren: YeshivotRouteChildren = {
  YeshivotIdRoute: YeshivotIdRoute,
}

const YeshivotRouteWithChildren = YeshivotRoute._addFileChildren(
  YeshivotRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  YeshivotRoute: YeshivotRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
