/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YeshivotRouteImport } from './routes/yeshivot'
import { Route as IndexRouteImport } from './routes/index'

const YeshivotRoute = YeshivotRouteImport.update({
  id: '/yeshivot',
  path: '/yeshivot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/yeshivot': typeof YeshivotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/yeshivot': typeof YeshivotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/yeshivot': typeof YeshivotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/yeshivot'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/yeshivot'
  id: '__root__' | '/' | '/yeshivot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  YeshivotRoute: typeof YeshivotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yeshivot': {
      id: '/yeshivot'
      path: '/yeshivot'
      fullPath: '/yeshivot'
      preLoaderRoute: typeof YeshivotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  YeshivotRoute: YeshivotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
